### PR TITLE
Upgrade to Morty

### PR DESCRIPTION
**Pull request by michal-mazurek**

### CODE REVIEW

**Comment by michal-mazurek** [comment]
This work was authored by Jon Nettleton.

**Comment by michal-mazurek** [comment]
Yes, I do believe we'll need to do that

**Comment by floion** [comment]
@michal-mazurek please rebase this PR.
Testing-wise, anything els left to do with the board you have now?

**Comment by floion** [comment]
@telphan please test this PR on a nitrogen6x board

**Comment by telphan** [comment]
@floion @michal-mazurek test was successful.

**Pull request merged**
