### PR TITLE
Release v2.15.1+rev1

### PR DESCRIPTION
**Pull request by spanceac**

### CODE REVIEW

**Comment by floion** [comment]
@spanceac looks like some commit logs are failing the integrity checks

**Comment by spanceac** [comment]
@resin-jenkins retest this please

**Comment by spanceac** [comment]
@resin-jenkins retest this please

**Comment by floion** [comment]
@resin-jenkins add to whitelist

**Comment by spanceac** [comment]
@resin-jenkins retest this please

**Comment by spanceac** [comment]
@resin-ci retest this please

**Comment by spanceac** [comment]
@resin-ci retest

**Comment by floion** [comment]
@spanceac versionist is added now to this PR so you'll need to amend this PR with the relevant changes (delete additions to Changelog.md file from your commits and use the `Changelog-entry` line instead for having versionbot add the relevant Changelog.md entries)

**Comment by floion** [comment]
Also, did you update Poky to a specific tag? If not, please use the latest available tag for the Poky release you want to use and specify that in the `Changelog-entry` item

**Comment by spanceac** [comment]
@resin-ci retest

**Comment by spanceac** [comment]
@resin-ci retest

**Comment by spanceac** [comment]
@resin-ci retest

**Comment by spanceac** [comment]
@resin-ci retest

**Pull request merged**
