### PR TITLE
BCM4330/BCM4329 support on cubox-i

### PR DESCRIPTION
**Pull request by agherzan**
@floion @telphan

### CODE REVIEW

**Comment by floion** [comment]
Would this have a high impact on size? I know we are already constrained by rootfs for resinhup.

**Comment by agherzan** [comment]
Good point @floion . It should be fine as the firmware is around 236K and the nvram config is 20K. And this is only included for cubox-i.

**Comment by agherzan** [comment]
ok to test

**Comment by Page-** [comment]
test

**Comment by floion** [comment]
Typo in the first commit log: "requred" instead of "required"

**Comment by agherzan** [comment]
@floion fixed typo.

**Comment by floion** [comment]
Sorry for not spotting it earlier, there is another typo in the same git log: vram instead of nvram

**Comment by floion** [comment]
LGTM

**Pull request merged**
